changelog:
	@if test -d "$(srcdir)/.git"; \
        then \
                echo Creating ChangeLog && \
                ( cd "$(top_srcdir)" && \
                  echo '# Generated by Makefile. Do not edit.'; echo; \
                  $(top_srcdir)/missing --run git log  \
                  --pretty=format:'commit:%n%ad  %an  <%ae>%ndescription:%n%s%n%brefs: %n%d %nfiles:'\
                  --stat --name-only --date=short --topo-order \
                  `test -n "$(GIT_LOG_START_COMMIT)" && echo "$(GIT_LOG_START_COMMIT)..HEAD" || \
                  echo ""`) | $(top_srcdir)/common/gitlog2ChangeLog > ChangeLog.tmp \
                && ( cat $(top_srcdir)/ChangeLog.old 2>/dev/null || echo ) >> ChangeLog.tmp \
                && cp -f ChangeLog.tmp $(distdir)/ChangeLog \
                && rm -f ChangeLog.tmp \
                || ( rm -f ChangeLog.tmp ; \
                     echo Failed to generate ChangeLog >&2 ); \
        else \
                echo A git clone is required to generate a ChangeLog >&2; \
        fi
